name: torch-kindle
channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - python=3.7
  - pytorch=1.7.1
  - torchvision=0.8.2
  - pip:
      - tabulate==0.8.9
      - timm==0.4.5
      - ptflops==0.6.4
      - tqdm==4.56.0
