name: torch-kindle
channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - python=3.8
  - pytorch=1.7.1
  - torchvision=0.8.2
  - timm=0.4.5
  - tabulate=0.8.9
  - pip:
      - tqdm==4.56.0
